### ISSUE TITLE
Robustify debug output

### ISSUE THREAD

**Issue by jhiemstrawisc** [PelicanPlatform/xrootd-s3-http#11]
Right now, it's extremely frustrating to debug this code, unless you can build from source and add print statements. We should implement various debug levels, similar to the way xrootd does the rest of its log levels.

**Comment by rw2** [comment]
@jhiemstrawisc is there someone who is the recognized expert in xrootd logging who could tell me/point me to the desired idioms?

**Comment by jhiemstrawisc** [comment]
Perhaps @matyasselmeci can point us in the right direction?

**Comment by matyasselmeci** [comment]
@bbockelm suggested that since you're writing a plugin, you should follow the example of another plugin instead of looking in XRootD itself, since logging code in XRootD may reach into the internals too much. [xrootd-multiuser](https://github.com/opensciencegrid/xrootd-multiuser/tree/master/src) is a fine example.

**Comment by rw2** [comment]
We are going to move forward with this using the TRACE macros that we see being used in several places. We'll do some instrumentation that allows us to get some timing information for transfer speeds. But if there ends up being specific patterns to add, let us know.

**Comment by rw2** [comment]
Looks like we were both typing at the same time. Thanks for the guidance.

**Comment by rw2** [comment]
Looked at this again today and have a few questions. @matyasselmeci suggested following the xrootd-multiuser example, which draws a line approximately at the interface between xrootd and the plugin. This makes sense.

Looking at the code, it looks like @bbockelm did some refactoring that accomplishes this goal. Is it possible this issue has been resolved and just not marked as closed?

**Comment by rw2** [comment]
Closed after conversation with @bbockelm confirming that the initial goal of this issue has been accomplished even if "there is always more that could be done". :-)
