### ISSUE TITLE
Better debug output if access/secret keys don't have correct permissions

### ISSUE THREAD

**Issue by jhiemstrawisc** [PelicanPlatform/xrootd-s3-http#12]
While setting up an S3 origin in Pelican, I mistakenly set the permissions to a set of access/secret keys owned by root to `600`. The plugin, running under user `xrootd`, did not make any noticeable errors that alerted me to the fact it couldn't read the keys.

**Comment by rw2** [comment]
Fixed in: https://github.com/PelicanPlatform/xrootd-s3-http/pull/34
