### ISSUE TITLE
Failed curl requests almost never report an error

### ISSUE THREAD

**Issue by jhiemstrawisc** [PelicanPlatform/xrootd-s3-http#25]
Running tests in Pelican frequently results in errors like:
```
time="2024-04-05T16:48:15Z" level=info msg="240405 16:48:15 16924 s3_S3File::Fstat: Failed to send HeadObject command: 0''" daemon=xrootd
```

It would be helpful if `0''` actually contained the error message and error string that's being set under the hood.

**Comment by rw2** [comment]
Can I get a way to reproduce this?

**Comment by jhiemstrawisc** [comment]
@rw2, I tried and failed a few times to reproduce this. I suspect it's been cleaned up already.

**Comment by rw2** [comment]
Ok, that makes sense. I closed a couple holes in that a while back.
