### ISSUE TITLE
`Stat` fails on a sub-directory when there's an object with the same prefix.

### ISSUE THREAD

**Issue by bbockelm** [PelicanPlatform/xrootd-s3-http#63]
If you have two objects in your bucket:
- `test.txt`
- `test/foo.txt`

Then an attempt to invoke `S3FileSystem::Stat` on `/test` will fail with an `ENOENT`.

This is because we currently try to do something clever -- we do a "listing" against the requested object name (`test`), asking for 1 entry in the response.  If it returns the object itself (`test`), we lie to xrootd and call it a file (that is, `st_mode` is `S_IFREG`).  If it returns the object name in the list of common prefixes, then we call it a "directory".  If neither applies, then we give an ENOENT.

However, this misses the fact that if there's an object name starting with the same prefix then the listing of `test` returns one object, `test.txt` and no common prefixes.  Hence, in the above case, we hit the `ENOENT`.

Looking at the `mc` client with `--debug` enabled, it appears they have a different approach:

1.  Perform a `HEAD` against the object name.  If it's a `200`, call it an "object".
2.  If the `HEAD` returns 404, then perform the listing against the object name with a trailing `/` (that is, list `test/` in the example above).  If it returns an object/common prefix, then assume it's a directory.

**Comment by rw2** [comment]
In my bucket I now have:
1.dat
1/1.dat

works: curl -k -X PROPFIND http://localhost:8080/my-magic-path/1
works: curl -k -X PROPFIND http://localhost:8080/my-magic-path/1/1.dat
doesn't work: curl -k -X PROPFIND http://localhost:8080/my-magic-path/1.dat

I think this is consistent with what @bbockelm is reporting. Mostly just putting it here as notes for a manual test.
